### ISSUE TITLE
integer temperature values do not work

### ISSUE THREAD

**Issue by danielegobbetti** [meyerd/pimatic-homegear#4]
when the temperature values are set to an integer value, the valve sets itself to 5 degrees. Half degree values work well.

I tried to fix it by using setFixed(1) to cast the value but it does not work.

**Comment by meyerd** [comment]
I encountered the bug myself, but haven't been able to pin down the exact cause. Maybe it has to do with the way xml-rpc transmits the temperature values. I guess the valve is set to 5 degrees (which corresponds to OFF, afaik) in case some invalid temperature value is sent.

**Comment by danielegobbetti** [comment]
For completeness, here are my tests (and their outcome):
- no change: integer temperatures (20) do not work, half degree temps (20.5) work well
- cast value to setFixed(1): integer temperatures (20.0) do not work, half degree temps (20.5) do not work
- cast value to setFixed(2): integer temperatures (20.00) do not work, half degree temps (20.50) do not work
- cast value to setFixed(1) and then to string:  integer temperatures ("20.0") do not work, half degree ("20.5") do not work

**Comment by danielegobbetti** [comment]
works for me \o/

**Comment by meyerd** [comment]
Awesome, thanks for debugging and fixing.
